### PR TITLE
Use `smoothedPumpFlow` to bootstap `smoothScalesFlow` kalman filter

### PR DESCRIPTION
**Pull request by judahrand**
The aim of this change is to try to make the flow graph reflect reality a bit more closely when using hardware scales by using the 'pump flow' as an initial estimate to give the 'scale flow' kalman filter. This helps prevent a large discontinuity to zero in the flow graph which doesn't exist in reality. 

I need to do a bit more testing and tweaking but this is an example of a graph produced with these changes (constant 2ml/sec requested).
image

### CODE REVIEW

**Comment by Zer0-bit** [comment]
Yeah this graph ain't showing shit, when there's no resistance at the puck the graph will look exactly like this with no changes.

**Comment by judahrand** [comment]
image

**Comment by judahrand** [comment]
image

**Comment by judahrand** [comment]
> Yeah this graph ain't showing shit, when there's no resistance at the puck the graph will look exactly like this with no changes.

Wdym? Is it wrong to use the pump flow as an estimate to feed the `scalesFlow` kalman filter?

**Comment by judahrand** [comment]
> > Yeah this graph ain't showing shit, when there's no resistance at the puck the graph will look exactly like this with no changes.
> 
> Wdym? Is it wrong to use the pump flow as an estimate to feed the `scalesFlow` kalman filter?

My understanding is that the predictive flow estimates and the weight estimates should, ideally, be identical once output has started. So it feels reasonable to help the kalman filter get near the correct `smoothedWeightFlow` value quickly by feeding it the predictive estimate? It helps to avoid the wind up in `smoothedWeightFlow`.

**Comment by Zer0-bit** [comment]
I would agree if you'd have a proper example, the graphs you're showing would behave exactly like this even with no changes.
How would it behave in such a scenario ?
image

**Comment by judahrand** [comment]
> I would agree if you'd have a proper example, the graphs you're showing would behave exactly like this even with no changes. How would it behave in such a scenario ? image

They wouldn't behave exactly the same. They'd look more like this:

PXL_20230409_073551421

But I agree that my changes need some more testing which I'll aim to do.

**Comment by Zer0-bit** [comment]
Ok raise the PR but this time against the right branch from the right branch fork pls and i'll test it.

**Pull request closed without merging**
