### PR TITLE
Add static analysis to CI/CD

### PR DESCRIPTION
**Pull request by MajorArkwolf**
## Changes
This PR does the following...
- Adds Clang-Tidy and CppCheck static analysis to each project that has a source file declaration
- Added new github action ``static-analysis`` that runs all projects. 
  - Flagging only medium and high warnings since there is quite a few low level warnings that would bloat this pr
  - Each step continues running regardless of previous failure to show all issues.
  - Made a separate task since the ``compile-sketch`` task is still the slowest, meaning this shouldn't increase the total time.
- Fixes most medium and high warnings that are shown on static analysis
  - src/log.cpp
    - The exception is log.cpp as modifying may expose dependencies in the header, so I have suppressed it for now.
    - renamed ``__FILENAME__`` to ``FILENAME`` due to ``__FILENAME__``  being a reserved key word
  - src/eeprom_data/eeprom_data.cpp
    - _copy is a reserved name, so changed function name to copy_t
    - Moved helper functions into the anonymous namespace to avoid ODR violations
  - src/lcd/nextion.cpp
    - called lcdCfg's default constructor to solve the uninitialised graphBrew
  - src/peripherals/esp_comms.cpp
    - Moved mcuComms into a singleton pattern so the throwing constructor can be caught or easily viewed. 
  - src/peripherals/scales.cpp
    - Moved LoadCells into a singleton pattern so the throwing constructor can be caught or easily viewed.  
      
## Check logs
See https://github.com/MajorArkwolf/gaggiuino/actions/runs/3963708244/jobs/6791849697 for full info
Logs of Clang-Tidy
```
src/eeprom_data/eeprom_data.cpp:181: [medium:warning] declaration uses identifier '_copy', which is reserved in the global namespace  [cert-dcl37-c,cert-dcl51-cpp]
src/log.cpp:7: [medium:warning] do not define a C-style variadic function; consider using a function parameter pack or currying instead  [cert-dcl50-cpp]
src/log.h:7: [medium:warning] declaration uses identifier '__FILENAME__', which is a reserved identifier  [cert-dcl37-c,cert-dcl51-cpp]
src/peripherals/esp_comms.cpp:4: [medium:warning] initialization of 'mcuComms' with static storage duration may throw an exception that cannot be caught  [cert-err58-cpp]
src/peripherals/scales.cpp:5: [medium:warning] initialization of 'LoadCells' with static storage duration may throw an exception that cannot be caught  [cert-err58-cpp]
```

Logs of Cppcheck
```
src/lcd/nextion.cpp:187: [high:error] Uninitialized struct member: lcdCfg.graphBrew [uninitStructMember]
```

### CODE REVIEW

**Comment by MajorArkwolf** [comment]
@kstam and @Zer0-bit this is ready for review.

@JackPoint I haven't used sonar but clang-tidy and cppcheck are both excellent, completely open-source tools and therefore have no desire to look further into sonar.

**Comment by JackPoint** [comment]
@MajorArkwolf if they are excellent, it works for me. Thanks for adding it and cleaning up. Did you plan to run these analyses for every pull request? That way, there is an extra pair of eyes that checks all the changes.

**Comment by MajorArkwolf** [comment]
Yep so you can run the static analysis from platform io through the check function and they have already been added to the GitHub actions as a seperate task that happens when a PR targets dev.

**Comment by kstam** [comment]
Great PR! 
One question on mcuComms.. why did you decide to go with singleton pattern? What if we want to talk to 2 mcus over different uarts in the future?

**Comment by MajorArkwolf** [comment]
mcuComms is currently a global variable within its translation unit, meaning that if you wanted to instantiate a second mcuComms you would need to change this code anyway. 

So the singleton hasn't imposed any new restrictions. What it has done however, is delayed it's construction until it gets used for the first time. This means that should it throw, it should be much easier to track down since we could get the call stack.

**Comment by kstam** [comment]
You're right! I somehow thought you were changing the mcu_comms library code but I see now you're actually introducing singleton to the users of the library 👍

**Review by kstam — APPROVED** [review]

**Comment by MajorArkwolf** [comment]
@kstam you will also need to approve the workflow to run

**Comment by Zer0-bit** [comment]
Great PR indeed, while i'm not a fan of this singleton approach it seems it's a necessary "evil" here.

**Comment by MajorArkwolf** [comment]
@Zer0-bit You may have forgot to hit approve

**Pull request merged**
