### PR TITLE
Add Kalman filtering to thermocouple reading

### PR DESCRIPTION
**Pull request by kholk**
Due to the nature of the hardware, the thermocouple wires will run near to AC wires, and the sensor itself is placed on a "grounded piece of metal" (the boiler). Depending on various factors, including DC PSU induced noise, sub-optimal grounding, and/or the EMI radiated from the nearby AC wires, the thermocouple may read an incorrect temperature up to 50% of total reads per 10 seconds.

While this is not a big issue for heater control (as it will not be able to get in a runaway situation), implementing Kalman filtering on the thermocouple readings will increase the precision of the heater and will, in some cases, also increase its efficiency with some slight power savings.

This was tested on a ... unsupported machine (but I had to Gaggiuino-ize it regardless), a Saeco Via Veneto DeLuxe (for the Italian market, and yes - it's grounded correctly :wink: ).

More than one parameter for the kalman filter were taken into consideration, but those are the ones that worked best (at least for me), as they're the sweet spot to not slow down temperature readings, while still reading smooth temperatures.

Cheers!

### CODE REVIEW

**Comment by Zer0-bit** [comment]
As temperature is a pretty linear reading and read errors are actually installation errors in a lot of the cases i would say that trying to filter those via software is totally the wrong approach as we want the system to react asap to any abnormal temperature readings.

**Comment by ash-j-f** [comment]
@kholk A comment for anyone who had similar issues who comes across this ticket; as mentioned this shouldn't be fixed in software. My non-Gaggiuno machine had similar issues until an alternative ungrounded thermocouple was used. See comments here for suggested alternate part: https://hackaday.io/project/192259/logs

Form the author at that link: "I'm not sure exactly why, but I know that the first thermistor I tried was grounded and had huge issues with electrical interference. Here's the correct one I used: https://www.aliexpress.com/item/1005003664282170.html?spm=a2g0o.order_list.order_list_main.37.21ef1802TWlqg9 "

**Comment by kholk** [comment]
Actually, my thermistor is ungrounded, and this did happen with three different parts.

Besides, if reacting ASAP means that a 250-500ms delay in reacting to temperature changes is unacceptable, I remind you that the boiler is, by nature, unable to severely overheat in 500ms.

In any case, the issue happens because the path between the boiler (hence, the thermistor) and the microcontroller board is crossing AC components (on the via veneto, poemia, etc the thermistor goes on top, crossing the boiler resistor wires and the pump wires), and there is *no* way of re-routing the thermistor wires such that it won't cross those.

Also, I can't see the AliExpress item as it's unavailable in my country for whatever reason.

Regards,
Angelo

**Comment by ash-j-f** [comment]
@kholk The thermocouple that worked for me on a non-Gaggiuino machine was "FTARR03 K type 0.5m" (I see it's available from places other than Ali Express too, fwiw).

**Pull request closed without merging**
