### PR TITLE
Fix pre infusion soak

### PR DESCRIPTION
**Pull request by judahrand**

### CODE REVIEW

**Comment by Zer0-bit** [comment]
Care to share what is this PR achieving ?

**Comment by judahrand** [comment]
> Care to share what is this PR achieving ?

I believe currently the soak phase of pre infusion is being skipped with hw scales.

**Comment by Zer0-bit** [comment]
No it's not, i just pulled and soak worked no issues.

**Comment by Zer0-bit** [comment]
So it's skipped if your puck prep is shit, as in if coffee starts dripping while it's not even finished the fill phase it means there's no point soaking that bitch cause it's going to be a waterfall.
Also this can be disabled by turning off the ```switch phase on restriction``` option.

**Comment by Zer0-bit** [comment]
> > No it's not, i just pulled and soak worked no issues.
> 
> Why does the soak phase have a weight restriction though?

Alternatively might also be skipped if scales have lots of noise 🤷

**Comment by Zer0-bit** [comment]
Anyhow i added this change yesterday literally so chances are there might be some bugs i'll test more see if i find anything.

**Pull request closed without merging**
