### PR TITLE
refactor(ts): network components to ts, fix typo

### PR DESCRIPTION
**Pull request by ckifer**
- typo + some small font adjustments
- refactor network components to TS
- fix bug where network drawer would continually refresh and not stop
  - remove `loading` from dependency array so network call is only made once 

### Testing
- connect to wifi -> disconnect from wifi
- network settings results and flow remain the same

### CODE REVIEW

**Comment by ckifer** [comment]
@kstam having issues connecting to wifi after your recent changes - everything else works (if password was previously saved it works)

```
I (wifi_setup.cpp:97): Connecting to WiFi [airCube-6C5]
E (476294) task_wdt: Task watchdog got triggered. The following tasks did not reset the watchdog in time:
E (476294) task_wdt:  - async_tcp (CPU 1)
E (476294) task_wdt: Tasks currently running:
E (476294) task_wdt: CPU 0: IDLE
E (476294) task_wdt: CPU 1: IDLE
E (476294) task_wdt: Aborting.

abort() was called at PC 0x42036468 on core 0


Backtrace: 0x4037733a:0x3fc98830 0x4037f001:0x3fc98850 0x403851cd:0x3fc98870 0x42036468:0x3fc988f0 0x403787bd:0x3fc98910 0x4212b433:0x3fcf56f0 0x42036ccd:0x3fcf5710 0x40380594:0x3fcf5730

ELF file SHA256: b7492f39c4e20297

Rebooting...
␀�ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0xc (RTC_SW_CPU_RST),boot:0x8 (SPI_FAST_FLASH_BOOT)
Saved PC:0x40376f48
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fce3808,len:0x44c
load:0x403c9700,len:0xbe4
load:0x403cc700,len:0x2a38
entry 0x403c98d4
```

**Comment by kstam** [comment]
You mean it's still not working after your changes? 

Just checking, have you flushed the latest webserver too? The connection API was changed from form data to JSON. But that was a while back 🤔 

I'll also check on my side in case I accidentally f'ed up something?

**Comment by ckifer** [comment]
Right - on every change I'll flash the webserver. After the change from multipart to JSON (it seems at least) I can no longer connect with ssid and password. I had connected previously and had my network saved so I don't think I tested after that change. 


The request gets sent to the webserver fine it's something in the call it seems. (But could be me)

**Comment by kstam** [comment]
Can you try this fix? 
https://github.com/Zer0-bit/gaggiuino/pull/509/files

**Review by kstam — APPROVED** [review]
LGTM

**Comment by ckifer** [comment]
> Can you try this fix? https://github.com/Zer0-bit/gaggiuino/pull/509/files
> 
> I can't reproduce it locally but it might be that my WiFI connection is stronger so the WDT doesn't kill my ESP

that did it - thanks!

**Pull request merged**
