### PR TITLE
Arduino controlled brew display timer

### PR DESCRIPTION
**Pull request by tylerjroach**
Similar to https://github.com/Zer0-bit/gaggiuino/pull/249 but for dev branch instead of nano.

I was unable to test, but has been tested by other STM user:
https://discord.com/channels/890339612441063494/890339805588783104/1008962071276290108

### CODE REVIEW

**Comment by tylerjroach** [comment]
Attaching images since you can't really see Nextion diffs.

nextion_brew_timer_update

nextion_descale_timer_update

Renamed minTimer to brewTimer. Changed timer on both brew graph and descale screen. 50ms update intervals

**Review by Zer0-bit — CHANGES_REQUESTED** [review]
You got conflicts for the nextion files as well as gaggiuino.ino

**Comment by tylerjroach** [comment]
Ah, I see I made changes on same day as others that got merged. I'll update here in a few

**Comment by tylerjroach** [comment]
Ready for review again. Merged dev, accepting dev Nextion files, then re-applied my changes.

**Comment by Zer0-bit** [comment]
> Ready for review again. Merged dev, accepting dev Nextion files, then re-applied my changes.

Just to confirm is the timer being handled only on the graph and descale screens ? As there's another brew screen that has a timer as well(only seconds though so way easier to deal with it there i guess.

**Comment by tylerjroach** [comment]
Ha, TIL. I didn't realize as I had never used the other brew screen. I'll add to that as well tonight.

**Comment by Zer0-bit** [comment]
Fuck with all the stuff going totally forgot about this PR, will check it's state tomorrow and merge it if no issues.

**Review by Zer0-bit — APPROVED** [review]

**Pull request merged**
