### PR TITLE
Add Github workflow for automatic Arduino compile

### PR DESCRIPTION
**Pull request by dlime**
Automatically verifies if gaggiuino.ino Sketch compiles on every commit / PR using Github actions

### CODE REVIEW

**Comment by dlime** [comment]
Notes :)
- a functioning example: https://github.com/dlime/gaggiuino/actions
- leftover file needs to be removed from this PR: `nextion-lcd_nx3224k024_011R.tft `

**Comment by Zer0-bit** [comment]
Nice idea!

**Comment by dlime** [comment]
> Nice idea!

An extra file sneaked in in this PR: `nextion-lcd_nx3224k024_011R.tft`
It's the Nextion HMI file regenerated for `nx3224k024_011R` model. Feel free to remove it :)

**Comment by Zer0-bit** [comment]
> > Nice idea!
> 
> An extra file sneaked in in this PR: `nextion-lcd_nx3224k024_011R.tft`
> It's the Nextion HMI file regenerated for `nx3224k024_011R` model. Feel free to remove it :)
Yeah i noticed but it ain't a big problem, will delete when will merge the new code as I've spent quite some time rewriting a lot of it as well as redesigning the while ui to be more user friendly plus to cater for new functionality in more "sane" way.

**Pull request merged**
